name: depremapp
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  flutter_hex_color: ^2.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  firebase_core: ^2.13.0
  flutter_riverpod: ^2.3.6
  http: ^0.13.6
  firebase_database: ^10.2.1
  cloud_firestore: ^4.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
