// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8UuiL56xQVwaRdWlksjsnCeXK1WLo3co',
    appId: '1:381885622348:web:f20b344806d8bf8d792ce9',
    messagingSenderId: '381885622348',
    projectId: 'depremyardim-a4151',
    authDomain: 'depremyardim-a4151.firebaseapp.com',
    storageBucket: 'depremyardim-a4151.appspot.com',
    measurementId: 'G-LCY46YJW3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdgoF5maIA-3dcV4yD420JvrcANdCtJ3g',
    appId: '1:381885622348:android:77d8be7ada9ea4d0792ce9',
    messagingSenderId: '381885622348',
    projectId: 'depremyardim-a4151',
    storageBucket: 'depremyardim-a4151.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAgPZ0FTK3MqNCjtMms9YFakDUmmp-4T0',
    appId: '1:381885622348:ios:074f2e63092fa99b792ce9',
    messagingSenderId: '381885622348',
    projectId: 'depremyardim-a4151',
    storageBucket: 'depremyardim-a4151.appspot.com',
    iosClientId: '381885622348-isnc63nj9u7itle4rhq3sp2ff3psnsgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.depremapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAgPZ0FTK3MqNCjtMms9YFakDUmmp-4T0',
    appId: '1:381885622348:ios:074f2e63092fa99b792ce9',
    messagingSenderId: '381885622348',
    projectId: 'depremyardim-a4151',
    storageBucket: 'depremyardim-a4151.appspot.com',
    iosClientId: '381885622348-isnc63nj9u7itle4rhq3sp2ff3psnsgc.apps.googleusercontent.com',
    iosBundleId: 'com.example.depremapp',
  );
}
